FROM centos:7
RUN yum update -y
RUN yum install java-openjdk -y
RUN  curl -O https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.67/bin/apache-tomcat-9.0.67.tar.gz
# ADD  https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.67/bin/apache-tomcat-9.0.67.tar.gz
RUN tar -xzf apache-tomcat-9.0.67.tar.gz  -C /opt
WORKDIR /opt
RUN mv apache-tomcat* apache-tomcat
COPY ./student.war /opt/apache-tomcat/bin/webapp/student.war
EXPOSE 8080
# CMD ["/opt/apache-tomcat/bin/catalina.sh","run"]
ENTRYPOINT ["/opt/apache-tomcat/bin/catalina.sh","run"]